### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by nsankar** [SamvelMK/FCMpy#11]
@SamvelMK   Hi, Thanks for developing this great package.

I am trying out fcmpy. 
What does the` sep_concept='->' `  do ? in this code

```
data = fcm.read_data(file_path= os.path.abspath('../unittests/test_cases/data_test.csv'), 
                      sep_concept='->', csv_sep=';')
```

Thank you.

**Comment by SamvelMK** [comment]
@nsankar Thanks for the feedback - gald to see you are using it. The sep_concept argument indicates the pattern by which the concepts are separated in the column headings in the data. For example, in the column heading you might have ('concept_A - Concept_B') than the separator would be '-'. As a default (to make it more clear) we use '->' to show that it's a causal link from concept_B to concept_B
